sub_areas = {
    "Cloud Engineering": [
        "Cloud Service Providers knowledge (AWS, Azure, GCP, etc.)",
        "Infrastructure as Code (IaC) with tools like Terraform, CloudFormation",
        "Containerization and Orchestration with Docker and Kubernetes",
        "Cloud Networking concepts (VPCs, VPNs, CDNs, load balancing)",
        "Cloud Security principles and IAM",
        "DevOps and CI/CD practices with tools like Jenkins, GitLab CI, GitHub Actions",
        "Database Management with SQL and NoSQL across cloud providers",
        "Scripting and Automation with Python, Bash, PowerShell",
        "Monitoring and Alerting for cloud resources and applications",
        "Auditing and Logging for governance, compliance, and security",
    ],
    "Data Engineering": [
        "Data Modeling and Warehousing",
        "ETL (Extract, Transform, Load) processes and tools",
        "Big Data processing frameworks (Hadoop, Spark, Presto)",
        "Programming languages (Python, SQL, Scala)",
        "Database management (SQL and NoSQL databases)",
        "Data pipeline orchestration tools (Airflow, Luigi, Prefect)",
        "Cloud platforms and services for data processing and storage",
        "Data visualization tools and libraries (Tableau, Power BI, Matplotlib, Seaborn)",
        "Machine Learning basics for data processing",
        "Version control systems (Git)",
    ],
    "Machine Learning Engineering": [
        "Proficiency in machine learning algorithms and concepts",
        "Deep learning frameworks (TensorFlow, PyTorch)",
        "Programming skills (Python, R)",
        "Data preprocessing and feature engineering",
        "Model evaluation and validation techniques",
        "Natural Language Processing (NLP) techniques",
        "Computer vision techniques and frameworks",
        "Big data technologies (Hadoop, Spark)",
        "Deployment of ML models (Docker, Kubernetes, cloud services)",
        "Experience with ML lifecycle management tools (MLflow, Kubeflow)",
        "Version control and collaboration tools (Git, GitHub)",
    ],
    "Backend Development": [
        "Advanced knowledge of backend programming languages (e.g., Python, Java, Node.js)",
        "Understanding of web frameworks (e.g., Django, Flask, Spring Boot)",
        "Database design and management (SQL, NoSQL)",
        "API design and development (REST, GraphQL)",
        "Microservices architecture and containerization (Docker, Kubernetes)",
        "Authentication and authorization standards (OAuth, JWT)",
        "Server and cloud infrastructure (AWS, Azure, GCP)",
        "Continuous integration and deployment (CI/CD) practices",
        "Unit testing and test-driven development (TDD)",
        "Scalability and performance optimization",
        "Version control systems (Git)",
        "Monitoring and Alerting for application performance and issues",
        "Auditing and Logging for tracking, troubleshooting, and security",
    ],
    "Frontend Development": [
        "Proficient in HTML, CSS, and JavaScript",
        "Experience with modern JavaScript frameworks and libraries (React, Angular, Vue.js)",
        "Responsive and mobile-first web design",
        "Cross-browser development and compatibility",
        "State management libraries (Redux, Vuex, Context API)",
        "TypeScript for strong typing in JavaScript applications",
        "Front-end build tools (Webpack, Gulp, npm)",
        "Version control systems (Git)",
        "Understanding of RESTful services and APIs",
        "Accessibility and web standards",
        "Performance optimization and debugging",
        "Experience with UI/UX design principles",
    ],
    # "Data Science": [
    #     "Exploratory Data Analysis (EDA)",
    #     "Statistical Modeling and Inference",
    #     "Data Visualization",
    #     "Big Data Technologies",
    #     "Predictive Analytics",
    #     "Time Series Analysis",
    #     "Recommender Systems",
    #     "Quantitative Methods",
    # ],
}


# Assign a color to each field
field_colors = {
    "Cloud Engineering": "skyblue",
    "Data Engineering": "blue",
    "Machine Learning Engineering": "red",
    "Backend Development": "green",
    "Frontend Development": "pink",
    # "Data Science": "purple",
}
